services:
  airdata:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.airdata
    profiles: ["distributed"]

  battery:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.battery
    profiles: ["distributed"]

  engine:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.engine
    profiles: ["distributed"]

  gps:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.gps
    profiles: ["distributed"]

  imu:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.imu
    profiles: ["distributed"]

  aggregation:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.aggregation
    depends_on:
      - airdata
      - battery
      - engine
      - gps
      - imu
    ports:
      - "50051:50051"
    profiles: ["distributed"]

  analysis:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.analysis
    depends_on:
      - aggregation
    ports:
      - "50052:50052"
    profiles: ["distributed"]

  update:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.update
    depends_on:
      - analysis
    ports:
      - "50054:50054"
    profiles: ["distributed"]

  server:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.server
    depends_on:
      - update
    ports:
      - "50053:50053"
    environment:
      - NODE_ID=0
      - NODE_PORT=server:50053
      - PYTHONUNBUFFERED=1
    profiles: ["distributed"]

  server1:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.server
    depends_on:
      - update
    ports:
      - "50055:50055"
    environment:
      - NODE_ID=1
      - NODE_PORT=server1:50055
      - PYTHONUNBUFFERED=1
    profiles: ["distributed"]

  server2:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.server
    depends_on:
      - update
    ports:
      - "50056:50056"
    environment:
      - NODE_ID=2
      - NODE_PORT=server2:50056
      - PYTHONUNBUFFERED=1
    profiles: ["distributed"]

  # -------- MONOLITH VERSION --------
  monolith:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.monolith
    ports:
      - "50053:50053"
    profiles: ["monolith"]

  #client:
  #  build:
  #    context: .
  #    dockerfile: Dockerfiles/Dockerfile.client
  #  depends_on:
  #    - server        # for distributed profile
      # - monolith    # use this instead for monolith profile
  #  stdin_open: true
  #  tty: true

  client:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.client
    depends_on:
      - server
    stdin_open: true
    tty: true
    profiles: ["distributed"]