FROM python:3.11-slim
WORKDIR /app
COPY src/ .
RUN pip install --no-cache-dir grpcio grpcio-tools
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. tpc.proto
CMD ["python", "participant.py"]