# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tpc_pb2 as tpc__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ParticipantStub(object):
    """Services ~

    Participant service — runs on every participant node
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestVote = channel.unary_unary(
                '/tcp.Participant/RequestVote',
                request_serializer=tpc__pb2.VoteRequest.SerializeToString,
                response_deserializer=tpc__pb2.VoteResponse.FromString,
                _registered_method=True)
        self.Deliver = channel.unary_unary(
                '/tcp.Participant/Deliver',
                request_serializer=tpc__pb2.Decision.SerializeToString,
                response_deserializer=tpc__pb2.Acknowledgement.FromString,
                _registered_method=True)
        self.NotifyDecisionPhase = channel.unary_unary(
                '/tcp.Participant/NotifyDecisionPhase',
                request_serializer=tpc__pb2.PhaseResult.SerializeToString,
                response_deserializer=tpc__pb2.PhaseAck.FromString,
                _registered_method=True)


class ParticipantServicer(object):
    """Services ~

    Participant service — runs on every participant node
    """

    def RequestVote(self, request, context):
        """Phase1: Coordinator → Participant (vote request)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deliver(self, request, context):
        """Phase2: Coordinator → Participant (final decision)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyDecisionPhase(self, request, context):
        """Phase2: Intra-node — voting phase → decision phase (same container)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ParticipantServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestVote,
                    request_deserializer=tpc__pb2.VoteRequest.FromString,
                    response_serializer=tpc__pb2.VoteResponse.SerializeToString,
            ),
            'Deliver': grpc.unary_unary_rpc_method_handler(
                    servicer.Deliver,
                    request_deserializer=tpc__pb2.Decision.FromString,
                    response_serializer=tpc__pb2.Acknowledgement.SerializeToString,
            ),
            'NotifyDecisionPhase': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyDecisionPhase,
                    request_deserializer=tpc__pb2.PhaseResult.FromString,
                    response_serializer=tpc__pb2.PhaseAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tcp.Participant', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tcp.Participant', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Participant(object):
    """Services ~

    Participant service — runs on every participant node
    """

    @staticmethod
    def RequestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tcp.Participant/RequestVote',
            tpc__pb2.VoteRequest.SerializeToString,
            tpc__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Deliver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tcp.Participant/Deliver',
            tpc__pb2.Decision.SerializeToString,
            tpc__pb2.Acknowledgement.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NotifyDecisionPhase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tcp.Participant/NotifyDecisionPhase',
            tpc__pb2.PhaseResult.SerializeToString,
            tpc__pb2.PhaseAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CoordinatorStub(object):
    """Coordinator service — runs on the server/coordinator node
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NotifyVotingPhase = channel.unary_unary(
                '/tcp.Coordinator/NotifyVotingPhase',
                request_serializer=tpc__pb2.PhaseResult.SerializeToString,
                response_deserializer=tpc__pb2.PhaseAck.FromString,
                _registered_method=True)
        self.StartTransaction = channel.unary_unary(
                '/tcp.Coordinator/StartTransaction',
                request_serializer=tpc__pb2.VoteRequest.SerializeToString,
                response_deserializer=tpc__pb2.Acknowledgement.FromString,
                _registered_method=True)


class CoordinatorServicer(object):
    """Coordinator service — runs on the server/coordinator node
    """

    def NotifyVotingPhase(self, request, context):
        """Phase2: Intra-node — decision phase → voting phase (same container)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartTransaction(self, request, context):
        """Entry point: external trigger to start a transaction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NotifyVotingPhase': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyVotingPhase,
                    request_deserializer=tpc__pb2.PhaseResult.FromString,
                    response_serializer=tpc__pb2.PhaseAck.SerializeToString,
            ),
            'StartTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTransaction,
                    request_deserializer=tpc__pb2.VoteRequest.FromString,
                    response_serializer=tpc__pb2.Acknowledgement.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tcp.Coordinator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tcp.Coordinator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Coordinator(object):
    """Coordinator service — runs on the server/coordinator node
    """

    @staticmethod
    def NotifyVotingPhase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tcp.Coordinator/NotifyVotingPhase',
            tpc__pb2.PhaseResult.SerializeToString,
            tpc__pb2.PhaseAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tcp.Coordinator/StartTransaction',
            tpc__pb2.VoteRequest.SerializeToString,
            tpc__pb2.Acknowledgement.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
