# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tpc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttpc.proto\x12\x03tcp\"\x07\n\x05\x45mpty\"\x1b\n\x08NodeInfo\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"P\n\x0bVoteRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x16\n\x0e\x63oordinator_id\x18\x02 \x01(\t\x12\x11\n\toperation\x18\x03 \x01(\t\"\\\n\x0cVoteResponse\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\x13\n\x0bvote_commit\x18\x03 \x01(\x08\x12\x0e\n\x06reason\x18\x04 \x01(\t\"2\n\x08\x44\x65\x63ision\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0e\n\x06\x63ommit\x18\x02 \x01(\x08\"K\n\x0f\x41\x63knowledgement\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\"E\n\x0bPhaseResult\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\r\n\x05ready\x18\x03 \x01(\x08\"4\n\x08PhaseAck\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x10\n\x08received\x18\x02 \x01(\x08\x32\xa9\x01\n\x0bParticipant\x12\x32\n\x0bRequestVote\x12\x10.tcp.VoteRequest\x1a\x11.tcp.VoteResponse\x12.\n\x07\x44\x65liver\x12\r.tcp.Decision\x1a\x14.tcp.Acknowledgement\x12\x36\n\x13NotifyDecisionPhase\x12\x10.tcp.PhaseResult\x1a\r.tcp.PhaseAck2\x7f\n\x0b\x43oordinator\x12\x34\n\x11NotifyVotingPhase\x12\x10.tcp.PhaseResult\x1a\r.tcp.PhaseAck\x12:\n\x10StartTransaction\x12\x10.tcp.VoteRequest\x1a\x14.tcp.Acknowledgementb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=18
  _globals['_EMPTY']._serialized_end=25
  _globals['_NODEINFO']._serialized_start=27
  _globals['_NODEINFO']._serialized_end=54
  _globals['_VOTEREQUEST']._serialized_start=56
  _globals['_VOTEREQUEST']._serialized_end=136
  _globals['_VOTERESPONSE']._serialized_start=138
  _globals['_VOTERESPONSE']._serialized_end=230
  _globals['_DECISION']._serialized_start=232
  _globals['_DECISION']._serialized_end=282
  _globals['_ACKNOWLEDGEMENT']._serialized_start=284
  _globals['_ACKNOWLEDGEMENT']._serialized_end=359
  _globals['_PHASERESULT']._serialized_start=361
  _globals['_PHASERESULT']._serialized_end=430
  _globals['_PHASEACK']._serialized_start=432
  _globals['_PHASEACK']._serialized_end=484
  _globals['_PARTICIPANT']._serialized_start=487
  _globals['_PARTICIPANT']._serialized_end=656
  _globals['_COORDINATOR']._serialized_start=658
  _globals['_COORDINATOR']._serialized_end=785
# @@protoc_insertion_point(module_scope)
